### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by saturnflyer** [runefs/maroon#3]
I'm working my way through the code but I'm getting an error when running the tests.

The error is in `get_args` where it runs

```
sexp = sexp[1][1..-1]
```

It seems that `sexp[1]` is returning nil so a `NoMethoError` is thrown when the `[1..-1]` is run.

I haven't dug deeper yet, but wanted to get feedback in case there was some small piece missing.

**Comment by runefs** [comment]
Strange. In which test? all tests work on my machine but I've yet to set up a second build environment so it's only in w.o.m.m. state

**Comment by saturnflyer** [comment]
I'll update this with a pull request from my branch to show you what I've got.

**Comment by saturnflyer** [comment]
I'm closing this issue. I accidentally created a separate pull request as I was trying to figure out how to get this issue connected to a request. All comments and code will be in #4 (work in progress)
