### ISSUE TITLE
Hi, intersecting sets of roles?

### ISSUE THREAD

**Issue by paradisaeidae** [runefs/maroon#6]
Thanks for Maroon and your video.
Do you know of a facility in DCI which allows/enables multiple concurrently active roles.
For instance, when a wiki session/persona/login has ('read'  by virtue of being regular user) and ('edit' by virtue of being admin user).

Thanks, MarkT

**Comment by runefs** [comment]
It's perfectly valid in DCI to have a role playing multiple roles at the same time and maroon supports this. However your example does not seem to be related to DCI roles but roles in the context of authentication. Those roles might or moght not be roles in DCI but it seems unlikely that the same object in the same context would play both a user and an administrator. There'd usually be a context for each interaction. for more info on DCI see http://runefs.com or follow the google group object-composition
